docs: fill out readme
ibm-telemetry/telemetry-config-schema pull request #2
Opened 2023-12-06 01:27 UTC by francinelucca

TODO:

- [ ] Add data on how to obtain projectID
- [ ] Add data on which endpoint to use

2023-12-06 19:07 UTC, mattrosno requested changes
Do we need to share that the JSX scope is used with React packages? Our non-technical audience might not know that.

2023-12-06 19:07 UTC, mattrosno commented on README.md
> +# yaml-language-server: $schema=https://unpkg.com/@ibm/telemetry-config-schema@0.3.0/dist/config.schema.json
Should this be

https://unpkg.com/@ibm/telemetry-config-schema@v1/dist/config.schema.json

or

https://unpkg.com/@ibm/telemetry-config-schema@v1/dist/config.schema.json

? You can use `vX` syntax with unpkg if you want it to use the latest of that major version.

2023-12-06 19:07 UTC, mattrosno commented on README.md
> +| `jsx` | Configuration for collecting telemetry data from JSX files. See [jsx schema](#jsx-schema) for more info.          | Optional | Object |
```suggestion
| `jsx` | Configuration for collecting telemetry data from JSX files. See [JSX schema](#jsx-schema) for more info.          | Optional | Object |
```

I think it's always `JSX` capitalization.

2023-12-06 19:07 UTC, mattrosno commented on README.md
> +## Jsx schema
```suggestion
## JSX schema
```

2023-12-06 19:07 UTC, mattrosno commented on README.md
> +Determines configuration for jsx scope collection.
```suggestion
Determines configuration for JSX scope collection.
```

2023-12-06 19:07 UTC, mattrosno commented on README.md
> +The jsx scope captures (jsx) element-specific usage data for the instrumented package. Specifically:
```suggestion
The JSX scope captures (JSX) element-specific usage data for the instrumented package. Specifically:
```

2023-12-06 19:07 UTC, mattrosno commented on README.md
> +The jsx config object has a single required `elements` key. This is an object that may be left empty
```suggestion
The JSX config object has a single required `elements` key. This is an object that may be left empty
```

2023-12-06 19:07 UTC, mattrosno commented on README.md
> +The `elements` key **must** be present inside the jsx config if jsx scope data is to be collected:
```suggestion
The `elements` key **must** be present inside the jsx config if JSX scope data is to be collected:
```

2023-12-06 19:27 UTC, francinelucca commented on README.md
> +# yaml-language-server: $schema=https://unpkg.com/@ibm/telemetry-config-schema@0.3.0/dist/config.schema.json
Fixed, thanks!!

2023-12-13 22:04 UTC, jdharvey-ibm approved these changes

2023-12-13 22:06 UTC, merged